"""FCG human-readable flowchart artifacts (port of output/flowchart-generator.js).

Emits two files per skill FCG JSON:
- Mermaid diagram source (.flow.mmd)
- Markdown report embedding the diagram plus bounded previews (.flow.md)

Pure visualization: no downstream verdict consumer reads these. The Python v6
envelope (json_generator.build_fcg_json) omits the debug paths/risks/source_sink
blocks that json-generator.js emitted, so those report sections degrade to empty
tables here exactly as the JS ?./|| [] fallbacks did — the mermaid diagram,
statistics, security transfer analysis, and node/edge previews carry the content.
"""

import json
import os
import re
import datetime


def generate_flowchart_artifacts(fcg_json, options=None):
    options = options or {}
    mermaid = _generate_mermaid(fcg_json)
    markdown = _generate_markdown_report(fcg_json, mermaid, options)
    return {"mermaid": mermaid, "markdown": markdown}


def save_flowchart_artifacts(fcg_json, markdown_path, mermaid_path):
    md_resolved = os.path.abspath(markdown_path)
    mmd_resolved = os.path.abspath(mermaid_path)
    md_dir = os.path.dirname(md_resolved)
    mmd_dir = os.path.dirname(mmd_resolved)
    if md_dir:
        os.makedirs(md_dir, exist_ok=True)
    if mmd_dir:
        os.makedirs(mmd_dir, exist_ok=True)
    artifacts = generate_flowchart_artifacts(fcg_json)
    with open(md_resolved, "w", encoding="utf-8") as fh:
        fh.write(artifacts["markdown"])
    with open(mmd_resolved, "w", encoding="utf-8") as fh:
        fh.write(artifacts["mermaid"])
    return {"markdown_path": md_resolved, "mermaid_path": mmd_resolved}

def _generate_mermaid(fcg_json):
    lines = []
    lines.append("flowchart TD")
    lines.append("  %% Auto-generated by Skill FCG Analyzer")

    for node in fcg_json.get("nodes") or []:
        label = _build_node_label(node)
        lines.append(f'  {node.get("id")}["{_escape_mermaid(label)}"]')

    for edge in fcg_json.get("edges") or []:
        edge_label = _build_edge_label(edge)
        arrow = "-.->" if edge.get("is_feedback_edge") else _edge_arrow(edge.get("type"))
        lines.append(
            f'  {edge.get("source")} {arrow}|{_escape_mermaid(edge_label)}| {edge.get("target")}'
        )

    lines.append("")
    lines.append("  %% Node classes")
    lines.append("  classDef source fill:#D8F3DC,stroke:#1B4332,color:#081C15,stroke-width:1px;")
    lines.append("  classDef sink fill:#FFE5D9,stroke:#9D0208,color:#370617,stroke-width:1px;")
    lines.append("  classDef critical fill:#FFD6A5,stroke:#6A040F,color:#370617,stroke-width:2px;")
    lines.append("  classDef intermediate fill:#E5E5E5,stroke:#6C757D,color:#212529,stroke-width:1px;")

    for node in fcg_json.get("nodes") or []:
        if node.get("is_critical"):
            lines.append(f'  class {node.get("id")} critical;')
        elif node.get("category") == "Source":
            lines.append(f'  class {node.get("id")} source;')
        elif node.get("category") == "Sink":
            lines.append(f'  class {node.get("id")} sink;')
        else:
            lines.append(f'  class {node.get("id")} intermediate;')

    return "\n".join(lines)

def _generate_markdown_report(fcg_json, mermaid, options=None):
    options = options or {}
    generated_at = (
        datetime.datetime.now(datetime.timezone.utc)
        .isoformat(timespec="milliseconds")
        .replace("+00:00", "Z")
    )
    top_path_count = int(options.get("topPathCount") or 30)
    top_cluster_count = int(options.get("topClusterCount") or 20)

    meta = fcg_json.get("meta") or {}
    lines = []
    lines.append("# FCG Human-Readable Flowchart")
    lines.append("")
    lines.append(f"- Skill: **{_safe(meta.get('skill_name'))}**")
    lines.append(f"- Version: **{_safe(meta.get('skill_version'))}**")
    lines.append(f"- Analysis Mode: **{_safe(meta.get('analysis_mode'))}**")
    lines.append(f"- Generated At: **{generated_at}**")
    lines.append(f"- Analyzer Timestamp: **{_safe(meta.get('analysis_timestamp'))}**")
    lines.append("")
    lines.append("## Diagram (Mermaid)")
    lines.append("")
    lines.append("```mermaid")
    lines.append(mermaid)
    lines.append("```")
    lines.append("")
    lines.append("## Statistics")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(fcg_json.get("statistics") or {}, indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    _append_path_compression(lines, fcg_json)
    _append_path_clusters(lines, fcg_json, top_cluster_count)
    _append_formal_semantics(lines, fcg_json)
    _append_top_paths(lines, fcg_json, top_path_count)
    _append_security_transfer(lines, fcg_json)
    _append_detail_preview(lines, fcg_json)
    return "\n".join(lines)

def _append_path_compression(lines, fcg_json):
    paths = fcg_json.get("paths") or {}
    compression = paths.get("path_compression") or {}
    lines.append("## Path Compression Summary")
    lines.append("")
    exact = compression.get("exact_path_count")
    if exact is None:
        exact = paths.get("source_to_sink_path_count_exact")
    if exact is None:
        exact = 0
    lines.append("- Exact Source->Sink path count: " + _safe(exact))
    lines.append("- Compression nodes: " + str(len(compression.get("compression_nodes") or [])))
    lines.append("- Compression edges: " + str(len(compression.get("compression_edges") or [])))
    lines.append("- Source/Sink pairs: " + str(len(compression.get("source_sink_pairs") or [])))
    lines.append("")
    lines.append("| source | sink | path_count | representative_length |")
    lines.append("| --- | --- | ---: | ---: |")
    pairs = (compression.get("source_sink_pairs") or [])[:20]
    for pair in pairs:
        lines.append(
            f"| {_escape_pipe(pair.get('source_node') or '')} "
            f"| {_escape_pipe(pair.get('sink_node') or '')} "
            f"| {_num(pair.get('path_count'))} "
            f"| {len(pair.get('representative_path_nodes') or [])} |"
        )
    if not (compression.get("source_sink_pairs") or []):
        lines.append("| - | - | 0 | 0 |")
    lines.append("")


def _append_path_clusters(lines, fcg_json, top_cluster_count):
    paths = fcg_json.get("paths") or {}
    lines.append("## Path Clusters (Semantic Groups)")
    lines.append("")
    lines.append(
        "| cluster_id | path_count | representative_path | template "
        "| risk_distribution | documents | triggers | policies |"
    )
    lines.append("| --- | ---: | --- | --- | --- | --- | --- | --- |")
    clusters = (paths.get("path_clusters") or [])[:top_cluster_count]
    for cluster in clusters:
        lines.append(
            f"| {_safe(cluster.get('cluster_id'))} "
            f"| {_num(cluster.get('path_count'))} "
            f"| {_safe(cluster.get('representative_path_id'))} "
            f"| {_escape_pipe(cluster.get('semantic_template') or '')} "
            f"| {_escape_pipe(_format_risk_distribution(cluster.get('risk_distribution')))} "
            f"| {_escape_pipe(_summarize_list(cluster.get('involved_documents')))} "
            f"| {_escape_pipe(_summarize_list(cluster.get('involved_triggers')))} "
            f"| {_escape_pipe(_summarize_list(cluster.get('involved_policies')))} |"
        )
    if not clusters:
        lines.append("| - | 0 | - | - | - | - | - | - |")
    lines.append("")

def _append_formal_semantics(lines, fcg_json):
    lines.append("## Formal Markdown Semantics")
    lines.append("")
    lines.append("| node | file | line | operation | targets | conditions | effects | evidence |")
    lines.append("| --- | --- | ---: | --- | --- | --- | --- | --- |")

    semantic_nodes = [n for n in (fcg_json.get("nodes") or []) if n.get("formal_semantics")]

    def _sort_key(node):
        loc = node.get("location") or {}
        return (str(loc.get("file") or ""), _num(loc.get("line")))

    semantic_nodes.sort(key=_sort_key)

    for node in semantic_nodes:
        semantics = node.get("formal_semantics") or {}
        loc = node.get("location") or {}
        evidence = semantics.get("evidence") or {}
        lines.append(
            f"| {_escape_pipe(node.get('name') or node.get('id') or '')} "
            f"| {_escape_pipe(loc.get('file') or '')} "
            f"| {_num(loc.get('line'))} "
            f"| {_escape_pipe(semantics.get('operation_type') or '')} "
            f"| {_escape_pipe(_format_semantic_targets(semantics.get('targets')))} "
            f"| {_escape_pipe(_format_semantic_conditions(semantics.get('conditions')))} "
            f"| {_escape_pipe(_summarize_list(semantics.get('effects'), 4))} "
            f"| {_escape_pipe(evidence.get('text') or '')} |"
        )

    if not semantic_nodes:
        lines.append("| - | - | 0 | - | - | - | - | - |")
    lines.append("")


def _append_top_paths(lines, fcg_json, top_path_count):
    paths = fcg_json.get("paths") or {}
    lines.append("## Top Source->Sink Paths")
    lines.append("")
    lines.append("| path_id | source | sink | length | risk | data_transferred |")
    lines.append("| --- | --- | --- | ---: | --- | --- |")

    node_map = {n.get("id"): n for n in (fcg_json.get("nodes") or [])}
    top_paths = (paths.get("source_to_sink_paths") or [])[:top_path_count]
    for path_item in top_paths:
        source_node = node_map.get(path_item.get("source_node")) or {}
        sink_node = node_map.get(path_item.get("sink_node")) or {}
        source_name = source_node.get("name") or path_item.get("source_node") or ""
        sink_name = sink_node.get("name") or path_item.get("sink_node") or ""
        lines.append(
            f"| {_safe(path_item.get('path_id'))} "
            f"| {_escape_pipe(source_name)} "
            f"| {_escape_pipe(sink_name)} "
            f"| {path_item.get('length') or 0} "
            f"| {_safe(path_item.get('risk_level'))} "
            f"| {_escape_pipe(path_item.get('data_transferred') or '')} |"
        )

    if not top_paths:
        lines.append("| - | - | - | 0 | - | - |")
    lines.append("")

def _append_security_transfer(lines, fcg_json):
    security = fcg_json.get("security_profile") or {}
    stats = security.get("statistics") or {}
    provenance = security.get("provenance_graph") or {}
    lines.append("## Security Transfer Analysis")
    lines.append("")
    lines.append(f"- Security Profile Version: {_safe(security.get('version') or '')}")
    lines.append(f"- Node Profiles: {len(security.get('node_profiles') or [])}")
    lines.append(f"- Doc Step Nodes: {_num(stats.get('doc_step_node_count'))}")
    lines.append(f"- Legacy Doc Operation Nodes: {_num(stats.get('doc_operation_node_count'))}")
    lines.append(f"- Label Flows: {len(security.get('label_flows') or [])}")
    lines.append(f"- Provenance Edges: {len(provenance.get('propagation_edges') or [])}")
    lines.append(f"- Observations: {len(security.get('observations') or [])}")
    lines.append(f"- Truncated: {_safe(bool(stats.get('truncated')))}")
    lines.append("")
    lines.append("### Observations")
    lines.append("")
    lines.append("| observation_id | label_flows | node | roles | labels | origins | boundary |")
    lines.append("| --- | --- | --- | --- | --- | --- | --- |")
    label_flow_map = {
        flow.get("label_flow_id"): flow for flow in (security.get("label_flows") or [])
    }
    for observation in (security.get("observations") or [])[:30]:
        flow_ids = observation.get("label_flow_ids") or []
        flows = [label_flow_map[i] for i in flow_ids if label_flow_map.get(i)]
        labels = [((f.get("label") or {}).get("label")) for f in flows]
        origins = [f.get("origin_node_name") or f.get("origin_node") for f in flows]
        lines.append(
            f"| {_safe(observation.get('observation_id'))} "
            f"| {_escape_pipe(_summarize_list(flow_ids, 4))} "
            f"| {_escape_pipe(observation.get('node_name') or observation.get('node_id') or '')} "
            f"| {_escape_pipe(_summarize_list(observation.get('node_roles'), 4))} "
            f"| {_escape_pipe(_summarize_list(labels, 4))} "
            f"| {_escape_pipe(_summarize_list(origins, 3))} "
            f"| {_escape_pipe(_format_boundary(observation.get('boundary')))} |"
        )
    if not (security.get("observations") or []):
        lines.append("| - | - | - | - | - | - | - |")
    lines.append("")

def _append_detail_preview(lines, fcg_json):
    lines.append("## Detail Preview")
    lines.append("")
    lines.append("### Nodes")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps((fcg_json.get("nodes") or [])[:80], indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    lines.append("### Edges")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps((fcg_json.get("edges") or [])[:120], indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    lines.append("### Source/Sink")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(fcg_json.get("source_sink") or {}, indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    lines.append("### Paths")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(_preview_paths(fcg_json.get("paths") or {}), indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    lines.append("### Risks")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps((fcg_json.get("risks") or [])[:80], indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")
    lines.append("### Security Profile")
    lines.append("")
    lines.append("```json")
    lines.append(json.dumps(
        _preview_security_profile(fcg_json.get("security_profile") or {}),
        indent=2, ensure_ascii=False))
    lines.append("```")
    lines.append("")


def _preview_paths(paths=None):
    paths = paths or {}
    compression = paths.get("path_compression") or {}
    return {
        "all_paths": (paths.get("all_paths") or [])[:60],
        "source_to_sink_paths": (paths.get("source_to_sink_paths") or [])[:60],
        "path_clusters": (paths.get("path_clusters") or [])[:40],
        "source_to_sink_path_count_exact": paths.get("source_to_sink_path_count_exact"),
        "path_compression": {
            **compression,
            "compression_nodes": (compression.get("compression_nodes") or [])[:80],
            "compression_edges": (compression.get("compression_edges") or [])[:120],
            "source_sink_pairs": (compression.get("source_sink_pairs") or [])[:80],
        },
    }

def _preview_security_profile(security=None):
    security = security or {}
    provenance = security.get("provenance_graph") or {}
    events = provenance.get("events") or {}
    return {
        "version": security.get("version") or "",
        "node_profiles": (security.get("node_profiles") or [])[:40],
        "label_flows": (security.get("label_flows") or [])[:80],
        "node_flow_sets": (security.get("node_flow_sets") or [])[:40],
        "provenance_graph": {
            "graph_id": provenance.get("graph_id") or "",
            "label_flow_nodes": (provenance.get("label_flow_nodes") or [])[:80],
            "propagation_edges": (provenance.get("propagation_edges") or [])[:120],
            "observation_links": (provenance.get("observation_links") or [])[:120],
            "events": {
                "routing": (events.get("routing") or [])[:80],
                "filtering": (events.get("filtering") or [])[:80],
                "merge": (events.get("merge") or [])[:60],
                "observation": (events.get("observation") or [])[:80],
                "truncation": (events.get("truncation") or [])[:80],
            },
            "statistics": provenance.get("statistics") or {},
        },
        "observations": (security.get("observations") or [])[:80],
        "statistics": security.get("statistics") or {},
    }


def _build_node_label(node):
    parts = [node.get("id"), node.get("name")]
    if node.get("category"):
        parts.append(f"category={node.get('category')}")
    if node.get("type"):
        parts.append(f"type={node.get('type')}")
    if node.get("is_critical"):
        parts.append("critical=true")
    return "\\n".join(_safe(p) for p in parts)


def _build_edge_label(edge):
    pieces = [edge.get("id") or "", edge.get("type") or "data_dependency"]
    if edge.get("is_feedback_edge"):
        pieces.insert(0, "feedback")
        if edge.get("feedback_plausibility"):
            pieces.append(edge.get("feedback_plausibility"))
    confidence = edge.get("confidence")
    if isinstance(confidence, (int, float)) and not isinstance(confidence, bool):
        pieces.append(f"conf={confidence:.2f}")
    data_flow = edge.get("data_flow") or {}
    if data_flow.get("from_param") or data_flow.get("to_param"):
        pieces.append(f"{data_flow.get('from_param') or '?'}->{data_flow.get('to_param') or '?'}")
    return " | ".join(p for p in pieces if p)


def _edge_arrow(edge_type):
    if edge_type == "doc_instruction":
        return "-.->"
    if edge_type == "control_flow":
        return "==>"
    if edge_type == "semantic":
        return "-->"
    return "-->"

def _escape_mermaid(value):
    s = str(value) if value else ""
    return (
        s.replace('"', '\\"')
        .replace("|", "/")
        .replace("\r", "")
        .replace("\n", "\\n")
    )


def _escape_pipe(value):
    return _safe(value).replace("|", "\\|")


def _safe(value):
    if value is None:
        return ""
    if value is True:
        return "true"
    if value is False:
        return "false"
    return str(value)


def _num(value):
    try:
        n = float(value or 0)
    except (TypeError, ValueError):
        n = 0.0
    if n == int(n):
        return int(n)
    return n


def _summarize_list(values, limit=2):
    lst = values if isinstance(values, list) else []
    if len(lst) == 0:
        return "-"
    if len(lst) <= limit:
        return ", ".join(_safe(x) for x in lst)
    return f"{', '.join(_safe(x) for x in lst[:limit])} ... (+{len(lst) - limit})"


def _format_risk_distribution(distribution=None):
    distribution = distribution or {}
    critical = _num(distribution.get("critical"))
    high = _num(distribution.get("high"))
    medium = _num(distribution.get("medium"))
    low = _num(distribution.get("low"))
    return f"critical={critical}, high={high}, medium={medium}, low={low}"


def _format_semantic_targets(targets):
    lst = targets if isinstance(targets, list) else []
    if len(lst) == 0:
        return "-"
    return _summarize_list([f"{t.get('type')}:{t.get('value')}" for t in lst], 4)


def _format_semantic_conditions(conditions):
    lst = conditions if isinstance(conditions, list) else []
    if len(lst) == 0:
        return "-"
    return _summarize_list([f"{c.get('type')}:{c.get('text')}" for c in lst], 3)


def _format_boundary(boundary=None):
    boundary = boundary or {}
    parts = [
        boundary.get("data_surface"),
        boundary.get("receiver_scope"),
        boundary.get("retention_scope"),
        boundary.get("trust_boundary"),
    ]
    joined = " / ".join(p for p in parts if p)
    return joined or "-"


def derive_flowchart_paths(json_output_path, custom_flowchart_path=""):
    if custom_flowchart_path:
        md_path = os.path.abspath(custom_flowchart_path)
        mmd_path = re.sub(r"\.md$", ".mmd", md_path, flags=re.IGNORECASE)
        return {
            "markdown_path": md_path,
            "mermaid_path": f"{md_path}.mmd" if mmd_path == md_path else mmd_path,
        }
    resolved_json = os.path.abspath(json_output_path)
    markdown_path = re.sub(r"\.json$", ".flow.md", resolved_json, flags=re.IGNORECASE)
    mermaid_path = re.sub(r"\.json$", ".flow.mmd", resolved_json, flags=re.IGNORECASE)
    return {"markdown_path": markdown_path, "mermaid_path": mermaid_path}







