"""Typed symbolic transfer specifications, before any Data identities exist.

These declarations describe one IR's single effect timeline.  Validation
checks syntax, references and coverage, never guesses an open opcode's meaning.
"""

from __future__ import annotations

from typing import Annotated, Any, Literal

from pydantic import BaseModel, BeforeValidator, ConfigDict, Field, JsonValue, StrictStr, StringConstraints, field_validator, model_validator, model_serializer

from skill_ir.data.models import _check_json_value, _require_list
from .compatibility import validate_event_operations, validate_operation_boundary


Text = Annotated[str, StringConstraints(min_length=1, pattern=r"\S")]
Index = Annotated[int, Field(strict=True, ge=0)]
# Symbolic element scopes are generated by propagation, never supplied as
# field selectors by the annotation model. Data.Path has a wider output domain.
SpecPath = Annotated[list[StrictStr | Index], BeforeValidator(_require_list), Field(min_length=1)]
LocationKind = Literal["runtime_context", "storage", "model_context", "remote", "tool", "user"]


class StrictSpec(BaseModel):
    model_config = ConfigDict(extra="forbid", strict=True, frozen=True)


class SpecEvidence(StrictSpec):
    basis: Literal["source", "cfg", "execution_model"]
    ref_id: Text
    quote: Text
    reason: Text


Evidences = Annotated[list[SpecEvidence], Field(min_length=1)]


class InputRef(StrictSpec):
    kind: Literal["input"]
    index: Index


class LocalRef(StrictSpec):
    kind: Literal["local"]
    name: Text


class LiteralRef(StrictSpec):
    kind: Literal["literal"]
    value: JsonValue

    @field_validator("value", mode="before")
    @classmethod
    def strict_json(cls, value: Any) -> Any:
        _check_json_value(value)
        return value


class AlternativesRef(StrictSpec):
    kind: Literal["alternatives"]
    items: list["ValueRef"]

    @field_validator("items")
    @classmethod
    def nonempty(cls, value: list["ValueRef"]) -> list["ValueRef"]:
        if not value:
            raise ValueError("alternatives must contain at least one candidate")
        return value


ValueRef = Annotated[InputRef | LocalRef | LiteralRef | AlternativesRef, Field(discriminator="kind")]
AlternativesRef.model_rebuild()


class OperandRef(StrictSpec):
    instruction_id: Text
    side: Literal["input", "output"]
    index: Index


class LocationSpec(StrictSpec):
    kind: LocationKind
    name: Text
    operand_refs: list[OperandRef]
    access_scope: Literal["task", "recipient", "shared", "public"]
    retention: Literal["task", "persistent"] | None

    @model_validator(mode="after")
    def boundary_attributes(self) -> "LocationSpec":
        if self.kind in {"storage", "runtime_context"} and self.retention is None:
            raise ValueError("storage and runtime context require an explicit retention")
        if self.kind in {"model_context", "remote", "user"} and self.access_scope == "task":
            raise ValueError("model, remote and user boundaries cannot be task-internal")
        return self

    @field_validator("operand_refs")
    @classmethod
    def unique_operand_refs(cls, value: list[OperandRef]) -> list[OperandRef]:
        identities = [(ref.instruction_id, ref.side, ref.index) for ref in value]
        if len(set(identities)) != len(identities):
            raise ValueError("duplicate location operand reference")
        return value


class AtomicSpec(StrictSpec):
    evidences: Evidences


class ReadOp(AtomicSpec):
    op: Literal["read"]
    location: Text
    output: Text


class ReceiveOp(AtomicSpec):
    op: Literal["receive"]
    location: Text
    inputs: list[ValueRef]
    output: Text


class DeliverOp(AtomicSpec):
    op: Literal["deliver"]
    inputs: list[ValueRef]
    target: Text
    when: ValueRef | None = None

    @model_serializer(mode="wrap")
    def omit_absent_condition(self, handler):
        result = handler(self)
        if self.when is None:
            result.pop("when", None)
        return result


class RawDeliverOp(AtomicSpec):
    """Conditional observations belong to the compiler, not the model."""
    op: Literal["deliver"]
    inputs: list[ValueRef]
    target: Text


class WriteOp(AtomicSpec):
    op: Literal["write"]
    target: Text
    mode: Literal["replace", "append", "delete"]
    input: ValueRef | None = None

    @model_validator(mode="after")
    def write_operand(self) -> "WriteOp":
        if self.mode == "delete" and self.input is not None:
            raise ValueError("delete write must not read a value")
        if self.mode != "delete" and self.input is None:
            raise ValueError("replace/append write requires input")
        return self


class SelectPartOp(AtomicSpec):
    op: Literal["select_part"]
    input: ValueRef
    path: SpecPath
    output: Text


class ExcludePartsOp(AtomicSpec):
    op: Literal["exclude_parts"]
    input: ValueRef
    paths: Annotated[list[SpecPath], Field(min_length=1)]
    output: Text

    @field_validator("paths")
    @classmethod
    def unique_paths(cls, value: list[SpecPath]) -> list[SpecPath]:
        if len({tuple(path) for path in value}) != len(value):
            raise ValueError("duplicate excluded path")
        return value


class FieldValue(StrictSpec):
    path: SpecPath
    value: ValueRef


class BuildMember(StrictSpec):
    path: SpecPath
    value: ValueRef
    when: ValueRef | None = None

    @model_validator(mode="after")
    def literal_condition(self):
        if isinstance(self.when, LiteralRef) and type(self.when.value) is not bool:
            raise ValueError("build member condition must be Boolean")
        return self


class UpdateFieldsOp(AtomicSpec):
    op: Literal["update_fields"]
    input: ValueRef
    updates: Annotated[list[FieldValue], Field(min_length=1)]
    output: Text


class BuildOp(AtomicSpec):
    op: Literal["build"]
    parts: list[BuildMember]
    output: Text
    container: Literal["object", "list"]

    @model_validator(mode="after")
    def conditional_members(self):
        if self.container == "list" and any(item.when is not None for item in self.parts):
            raise ValueError("conditional build members require an object container")
        return self


class ComputeOp(AtomicSpec):
    op: Literal["compute"]
    inputs: list[ValueRef]
    dependencies: list[Literal["derived", "possible"]]
    output: Text

    @model_validator(mode="after")
    def dependency_arity(self) -> "ComputeOp":
        if len(self.inputs) != len(self.dependencies):
            raise ValueError("compute dependencies must match inputs one-to-one")
        return self


class FilterItemsOp(AtomicSpec):
    op: Literal["filter_items"]
    input: ValueRef
    predicate: Text
    output: Text


AtomicOp = Annotated[
    ReadOp | ReceiveOp | DeliverOp | WriteOp | SelectPartOp | ExcludePartsOp
    | UpdateFieldsOp | BuildOp | ComputeOp | FilterItemsOp,
    Field(discriminator="op"),
]

RawAtomicOp = Annotated[
    ReadOp | ReceiveOp | RawDeliverOp | WriteOp | SelectPartOp | ExcludePartsOp
    | UpdateFieldsOp | BuildOp | ComputeOp | FilterItemsOp,
    Field(discriminator="op"),
]


class EffectSpec(StrictSpec):
    effect_index: Index | None
    atomic_ops: Annotated[list[AtomicOp], Field(min_length=1)]


class RawEffectSpec(StrictSpec):
    effect_index: Index | None
    atomic_ops: Annotated[list[RawAtomicOp], Field(min_length=1)]


class ProcessingSpec(StrictSpec):
    kind: Literal["processing"]
    mode: Literal["model", "local", "default"]
    events: Annotated[list[RawEffectSpec], Field(min_length=1)]
    returns: list[ValueRef] = Field(default_factory=list)
    evidences: Evidences

    @model_validator(mode="after")
    def explicit_local_boundary(self):
        if self.mode != "local" and self.returns:
            raise ValueError("returns belongs only to an explicit local processing boundary")
        if self.mode == "local":
            if "returns" not in self.model_fields_set:
                raise ValueError("local processing requires explicit returns, possibly empty")
            if not any(item.basis in {"source", "cfg"} for item in self.evidences):
                raise ValueError("local processing requires source or CFG mechanism evidence")
        return self


class RawForEachSpec(StrictSpec):
    kind: Literal["for_each"]
    collection: ValueRef
    item: Text
    body: Annotated[list[ProcessingSpec], Field(min_length=1)]
    evidences: Evidences


class ForEachSpec(StrictSpec):
    kind: Literal["for_each"]
    collection: ValueRef
    item: Text
    body: Annotated[list[EffectSpec], Field(min_length=1)]
    evidences: Evidences


class OutputBinding(StrictSpec):
    output_index: Index
    value: ValueRef
    evidences: Evidences


class OperationPosition(StrictSpec):
    event_index: Index
    op_index: Index
    body_event_index: Index | None = None


class Precedence(StrictSpec):
    before: OperationPosition
    after: OperationPosition


class IRTransferSpec(StrictSpec):
    order: Literal["fixed", "partial"]
    precedence: list[Precedence]
    events: list[EffectSpec | ForEachSpec]
    output_bindings: list[OutputBinding]


class RawIRTransferSpec(StrictSpec):
    order: Literal["fixed", "partial"]
    events: list[Annotated[ProcessingSpec | RawForEachSpec, Field(discriminator="kind")]]
    output_bindings: list[OutputBinding]


def iter_scoped_events(spec: IRTransferSpec):
    """Yield (outer event index, body index or None, effect) in semantic order."""
    for index, event in enumerate(spec.events):
        if isinstance(event, ForEachSpec):
            for body_index, child in enumerate(event.body):
                yield index, body_index, child
        else:
            yield index, None, event


def iter_effect_events(spec: IRTransferSpec):
    for _, _, event in iter_scoped_events(spec):
        yield event


def flatten_raw_spec(spec: RawIRTransferSpec) -> IRTransferSpec:
    """Remove processing boundaries solely for shared reference validation."""
    events = []
    edges = set()
    def extend_segment(segment, target, outer=None):
        start = len(target)
        target.extend(EffectSpec.model_validate(child.model_dump(mode="python")) for child in segment.events)
        positions = [(e if outer is None else outer, None if outer is None else e, o)
                     for e in range(start, len(target)) for o in range(len(target[e].atomic_ops))]
        edges.update(zip(positions, positions[1:]))
    for event in spec.events:
        if isinstance(event, ProcessingSpec):
            extend_segment(event, events)
        else:
            body = []
            for processing in event.body:
                extend_segment(processing, body, outer=len(events))
            events.append(ForEachSpec(kind="for_each", collection=event.collection, item=event.item,
                                     body=body,
                                     evidences=event.evidences))
    def coordinate(key):
        return (key[0], -1 if key[1] is None else key[1], key[2])
    precedence = [Precedence(before=position_value(before), after=position_value(after))
                  for before, after in sorted(edges, key=lambda pair: (coordinate(pair[0]), coordinate(pair[1])))]
    return IRTransferSpec(order=spec.order, precedence=precedence, events=events, output_bindings=spec.output_bindings)


def value_refs(operation: AtomicOp) -> list[ValueRef]:
    """Return used symbolic values in operand order, preserving repetitions."""
    from .uses import value_uses
    return [use.value for use in value_uses(operation)]


def _local_names(ref: ValueRef) -> set[str]:
    if isinstance(ref, LocalRef):
        return {ref.name}
    if isinstance(ref, AlternativesRef):
        return set().union(*(_local_names(item) for item in ref.items))
    return set()


def _validate_ref(ref: ValueRef, instruction: dict, definitions: dict[str, int], position: int, *, uncertain: bool, inside_alternatives: bool = False) -> None:
    if isinstance(ref, InputRef):
        if ref.index >= len(instruction.get("inputs", [])):
            raise ValueError(f"input reference out of range: {instruction['id']}/{ref.index}")
        if instruction["inputs"][ref.index]["type"] == "external_resource":
            raise ValueError("resource identity is not a data payload; use an evidenced literal or read")
    elif isinstance(ref, LocalRef):
        if ref.name not in definitions:
            raise ValueError(f"undefined local reference: {instruction['id']}/{ref.name}")
        if definitions[ref.name] >= position and not (uncertain and inside_alternatives):
            raise ValueError(f"local reference precedes definition: {instruction['id']}/{ref.name}")
    elif isinstance(ref, AlternativesRef):
        for item in ref.items:
            _validate_ref(item, instruction, definitions, position, uncertain=uncertain, inside_alternatives=True)
        if uncertain and not any(not _local_names(item) or all(definitions[name] < position for name in _local_names(item)) for item in ref.items):
            raise ValueError("uncertain alternatives must preserve an already available candidate")


def _validate_fields(fields: list[FieldValue], *, container: str | None = None) -> None:
    paths = [tuple(item.path) for item in fields]
    if len(paths) != len(set(paths)):
        raise ValueError("duplicate field path")
    for left in paths:
        for right in paths:
            if left != right and len(left) < len(right) and right[:len(left)] == left:
                raise ValueError("overlapping field paths require separate ordered operations")
        if container == "object" and not isinstance(left[0], str):
            raise ValueError("object construction requires field-name root paths")
        if container == "list" and type(left[0]) is not int:
            raise ValueError("list construction requires index root paths")
    if container is not None:
        children: dict[tuple, set] = {}
        for path in paths:
            for depth, member in enumerate(path):
                children.setdefault(path[:depth], set()).add(member)
        for members in children.values():
            indexes = {member for member in members if type(member) is int}
            if indexes and len(indexes) != len(members):
                raise ValueError("construction cannot mix object fields and list indexes at one path")
            if indexes and indexes != set(range(len(indexes))):
                raise ValueError("complete list construction requires consecutive indexes starting at zero")


def validate_specs(cfg: dict[str, Any], annotation: Any) -> None:
    """Validate a parsed joint annotation; quoted text is checked upstream."""
    if isinstance(annotation, dict):
        from skill_ir.security_profile.models import AnnotationPayload
        annotation = AnnotationPayload.model_validate(annotation)
    profiles = annotation.profiles
    locations = annotation.locations
    specs = annotation.transfer_specs
    instructions = {item["id"]: item for block in cfg["blocks"].values() for item in block["instructions"]}
    expected = set(instructions)
    if set(specs) != expected or set(profiles) != expected:
        raise ValueError("transfer/profile coverage must match every actual IR")
    identities: set[tuple[str, str]] = set()
    for location_id, location in locations.items():
        if not location_id.strip():
            raise ValueError("location ID must not be blank")
        identity = location.kind, location.name
        if identity in identities:
            raise ValueError("duplicate location identity")
        identities.add(identity)
        for ref in location.operand_refs:
            instruction = instructions.get(ref.instruction_id)
            if instruction is None or ref.index >= len(instruction.get(ref.side + "s", [])):
                raise ValueError("location operand reference does not exist")
    for ir_id, spec in specs.items():
        is_raw = isinstance(spec, RawIRTransferSpec)
        if is_raw:
            spec = flatten_raw_spec(spec)
        else:
            validate_precedence(spec)
        instruction = instructions[ir_id]
        effects = profiles[ir_id].effects
        indices = [event.effect_index for event in iter_effect_events(spec) if event.effect_index is not None]
        if indices != list(range(len(effects))):
            raise ValueError(f"event effect positions must match profile exactly: {ir_id}")
        for event in iter_effect_events(spec):
            effect = None if event.effect_index is None else effects[event.effect_index]
            validate_event_operations(effect, [operation.op for operation in event.atomic_ops])
        bindings = [item.output_index for item in spec.output_bindings]
        if sorted(bindings) != list(range(len(instruction.get("outputs", [])))):
            raise ValueError(f"output bindings must cover each actual output exactly once: {ir_id}")
        definitions, count = _validate_scope(
            spec.events, instruction, effects, locations, uncertain=spec.order == "partial")
        for binding in spec.output_bindings:
            _validate_ref(binding.value, instruction, definitions, count, uncertain=False)
        from .uses import request_pairs
        request_pairs(spec)
    if hasattr(annotation, "sink_boundaries"):
        from skill_ir.security_profile.boundaries import derive_sink_boundaries
        if annotation.sink_boundaries != derive_sink_boundaries(locations, specs, profiles):
            raise ValueError("sink boundaries must match the deterministic compiled derivation")


def _validate_scope(events, instruction, effects, locations, *, uncertain, external=None, in_foreach=False):
    definitions = dict(external or {})
    positions = []
    count = 0
    for event in events:
        if isinstance(event, ForEachSpec):
            if in_foreach:
                raise ValueError("nested for_each is not supported")
            positions.append((count, event, None))
            count += 1
        else:
            for operation in event.atomic_ops:
                positions.append((count, event, operation))
                output = getattr(operation, "output", None)
                if output is not None:
                    if output in definitions:
                        raise ValueError(f"duplicate local definition: {instruction['id']}/{output}")
                    definitions[output] = count
                count += 1
    dependencies = {}
    for position, event, operation in positions:
        if isinstance(event, ForEachSpec):
            _validate_ref(event.collection, instruction, definitions, position, uncertain=False)
            outer = {name: -1 for name, at in definitions.items() if at < position}
            if event.item in definitions:
                raise ValueError("for_each item must not shadow an outer local")
            outer[event.item] = -1
            _validate_scope(event.body, instruction, effects, locations, uncertain=uncertain,
                            external=outer, in_foreach=True)
            continue
        if in_foreach and isinstance(operation, (ReadOp, ReceiveOp, WriteOp)):
            raise ValueError("for_each body must not read, receive, or write shared state")
        effect = None if event.effect_index is None else effects[event.effect_index]
        location_id = getattr(operation, "location", getattr(operation, "target", None))
        if location_id is not None and location_id not in locations:
            raise ValueError(f"undefined location: {location_id}")
        validate_operation_boundary(operation.op, effect, None if location_id is None else locations[location_id].kind,
                                    dependencies=operation.dependencies if isinstance(operation, ComputeOp) else None,
                                    input_count=len(operation.inputs) if isinstance(operation, DeliverOp) else None)
        if isinstance(operation, DeliverOp) and operation.when is not None:
            if effect != "model_observe":
                raise ValueError("conditional delivery is reserved for compiled model observation")
            if isinstance(operation.when, LiteralRef) and type(operation.when.value) is not bool:
                raise ValueError("observation condition must be Boolean")
        if isinstance(operation, UpdateFieldsOp):
            _validate_fields(operation.updates)
        if isinstance(operation, BuildOp):
            _validate_fields(operation.parts, container=operation.container)
        refs = value_refs(operation)
        for ref in refs:
            _validate_ref(ref, instruction, definitions, position, uncertain=uncertain)
            if in_foreach:
                _reject_context_input(ref, instruction)
        from .uses import value_uses, static_condition
        for use in value_uses(operation):
            if use.role == "control":
                static_condition(use.value, instruction)
        output = getattr(operation, "output", None)
        if output is not None:
            dependencies[output] = set().union(*(_local_names(ref) for ref in refs)) if refs else set()
    visiting, visited = set(), set()
    def visit(name):
        if name in visiting:
            raise ValueError(f"cyclic local definitions: {instruction['id']}/{name}")
        if name in visited:
            return
        visiting.add(name)
        for parent in dependencies.get(name, set()):
            visit(parent)
        visiting.remove(name)
        visited.add(name)
    for name in definitions:
        visit(name)
    return definitions, count


def _reject_context_input(ref, instruction):
    if isinstance(ref, InputRef) and instruction["inputs"][ref.index]["type"] == "context_key":
        raise ValueError("for_each body must not depend on mutable context_key operands")
    if isinstance(ref, AlternativesRef):
        for child in ref.items:
            _reject_context_input(child, instruction)


def iter_spec_evidence(annotation: Any):
    """Yield each scope, operation and output evidence in a raw or compiled spec."""
    def effects(events):
        for event in events:
            if isinstance(event, (RawForEachSpec, ForEachSpec)):
                yield from event.evidences
                yield from effects(event.body)
            elif isinstance(event, ProcessingSpec):
                yield from event.evidences
                yield from effects(event.events)
            else:
                for operation in event.atomic_ops:
                    yield from operation.evidences
    for spec in annotation.transfer_specs.values():
        yield from effects(spec.events)
        for binding in spec.output_bindings:
            yield from binding.evidences


def operation_key(position):
    """Stable coordinates; None marks the ordinary (non-member) scope."""
    if isinstance(position, dict):
        position = OperationPosition.model_validate(position)
    return (position.event_index, position.body_event_index, position.op_index)


def position_value(key):
    event, body, op = key
    return {"event_index": event, "body_event_index": body, "op_index": op}


def operation_items(spec):
    return {(e, b, o): op for e, b, event in iter_scoped_events(spec)
            for o, op in enumerate(event.atomic_ops)}


def _required_local_names(ref):
    # Alternatives are may-values: an early observation may use the already
    # available candidate while another arrangement can include a later value.
    return {ref.name} if isinstance(ref, LocalRef) else set()


def structural_precedence(spec):
    """Causal constraints derivable without interpreting free-form text."""
    operations = operation_items(spec)
    edges = set()
    definitions = {}
    for (e, b, o), op in operations.items():
        if o:
            edges.add(((e, b, o - 1), (e, b, o)))
        if hasattr(op, "output"):
            definitions[(None if b is None else e, op.output)] = (e, b, o)
    for key, op in operations.items():
        scope = None if key[1] is None else key[0]
        for ref in value_refs(op):
            for name in _required_local_names(ref):
                origin = definitions.get((scope, name), definitions.get((None, name)))
                if origin is not None:
                    edges.add((origin, key))
    # A collection and every outer value used by a member scope must be ready
    # before that scope starts. No artificial operation is added to the wire.
    for e, event in enumerate(spec.events):
        if isinstance(event, ForEachSpec):
            for name in _local_names(event.collection):
                origin = definitions.get((None, name))
                if origin is not None:
                    for key in operations:
                        if key[0] == e and key[1] is not None:
                            edges.add((origin, key))
    return edges


def precedence_edges(spec):
    edges = {(operation_key(item.before), operation_key(item.after)) for item in spec.precedence}
    edges |= structural_precedence(spec)
    from .uses import request_precedence
    edges |= request_precedence(spec)
    if spec.order == "fixed":
        keys = list(operation_items(spec))
        edges.update(zip(keys, keys[1:]))
    return edges


def precedence_closure(spec):
    nodes = set(operation_items(spec))
    edges = precedence_edges(spec)
    following = {node: set() for node in nodes}
    for before, after in edges:
        following[before].add(after)
    changed = True
    while changed:
        changed = False
        for node in nodes:
            expanded = following[node] | set().union(*(following[child] for child in following[node]))
            if expanded != following[node]:
                following[node] = expanded
                changed = True
    return following


def validate_precedence(spec):
    nodes = set(operation_items(spec))
    pairs = [(operation_key(item.before), operation_key(item.after)) for item in spec.precedence]
    if len(pairs) != len(set(pairs)):
        raise ValueError("duplicate precedence constraint")
    if any(before not in nodes or after not in nodes for before, after in pairs):
        raise ValueError("precedence references a nonexistent operation")
    if any(before == after for before, after in pairs):
        raise ValueError("precedence cannot order an operation before itself")
    closure = precedence_closure(spec)
    if any(node in after for node, after in closure.items()):
        raise ValueError("cyclic precedence constraints")
    # References to the same member scope remain local. A body cannot depend
    # on a later external operation while earlier body work must precede it;
    # this would require interleaving a symbolic collection with shared state,
    # outside the single-level member model.
    for e, event in enumerate(spec.events):
        if isinstance(event, ForEachSpec):
            members = {key for key in nodes if key[0] == e and key[1] is not None}
            for outer in nodes - members:
                if any(outer in closure[member] for member in members) and any(member in closure[outer] for member in members):
                    raise ValueError("precedence requires unsupported scope/shared-state interleaving")


def schedule_dependencies(spec, *, outer_event=None):
    """Collapse member scopes for outer scheduling, retaining atomic granularity.

    Processing segments are never scheduling atoms: their primitive operations
    can interleave with operations of other segments if no constraint forbids it.
    """
    result = {}
    def project(key):
        e, b, o = key
        if outer_event is None:
            return (e, -1) if b is not None else (e, o)
        return (b, o) if e == outer_event and b is not None else None
    for key in operation_items(spec):
        target = project(key)
        if target is not None:
            result.setdefault(target, set())
    for before, after in precedence_edges(spec):
        left, right = project(before), project(after)
        if left is not None and right is not None and left != right:
            result[right].add(left)
    return result
