"""One abstract runtime contract shared by annotation and static propagation.

The contract bounds possible executions; it does not describe a measured trace
or select a concrete agent runtime. Its English rules are the sole executable
definition. Source extraction and source/CFG review do not inherit its defaults.
"""

from __future__ import annotations

from copy import deepcopy
import hashlib
import json
from typing import Any


CONTRACT_VERSION = "skillflow-abstract-runtime-v5"

# Stable evidence IDs. A revised meaning or text requires a new contract version.
_RULES = (
    ("EM01", "Source scope default: a natural-language request for a field from a container does not establish a key-only read mechanism. Preserve the related source whole as a possible acquisition scope unless an explicit interface or mechanism restricts the read or returned content. Merely needing one field, using a local tool, or naming a getter in an opcode is not such evidence. Keep source identity, local read scope, returned content, and the selected target value separate. Express the requested field selection without replacing the source whole by an independent field source. The whole may remain unexpanded; do not invent other fields, sensitivity labels, file paths, or access to unrelated runtime state. This is a conservative analysis default, not proof that an actual execution reads the whole, and not an extra source-level CFG action."),
    ("EM02", "Tool-return default: content returned by an agent tool is retained as possibly entering the next model request unless an explicit content-routing or isolation mechanism restricts it. Apply this default to the returned version, not to everything the tool internally read. A local process can scan a whole file and return only a selected line; the scan alone does not expose the whole file to the model. Explicit local-only processing, result-only return, model-invisible storage, and credential injection or handles constrain this default. Such exceptions require supported source, code, or interface evidence, not executor labels or wishful implementation choices. This is a may-analysis assumption, not a measured event or a fact about every agent."),
    ("EM03", "Model visibility boundary: content placed in a model request constitutes model_observe of that content, not proof that the model understands, remembers, or later discloses it. Local reading and LLM scheduling alone do not establish that boundary. For content acquired for the agent's natural-language processing with no explicit isolation or restricted routing, retain possible model observation of the acquired version. Cite this rule for the default and source/CFG evidence for the acquisition to which it applies. An agent_runtime or tool label, a local-sounding opcode, or a desired field is not evidence of model invisibility. Defaults apply normally when execution details are absent. A necessary judgment that cannot be supported by the available material is an explicit cannot_assess failure, not an empty successful annotation."),
    ("EM04", "Data versions and explicit mechanisms: distinguish model processing from local processing. A model selecting or transforming content observes its input version; explicitly local processing whose result alone is returned exposes that result instead, without inventing observation of all internal inputs. An evidenced key-only interface limits the acquired or returned value, while model visibility is assessed separately. A supported model-invisible credential proxy or isolated handle is not secret plaintext. Subsequent filtering cannot revoke an earlier observation. Selection, masking, encryption, and summarization use transform when supported, but do not prove sensitivity removal. Distinct observation stages require distinct phase evidence; do not invent their count or impose protection-first ordering."),
    ("EM05", "Declarations and defaults: a prohibition or instruction to use only a specified field does not itself implement filtering, masking, isolation, or a key-only interface. Preserve explicit restrictions without inventing protective actions to satisfy them. Contract defaults may supply possible analysis events for an existing action; they cannot create an unrelated acquisition or source-level business action. Clearly identify default-based inferences as possible under this contract, never as explicit source requirements, observed runtime events, or verified security guarantees."),
    ("EM06", "Independent interaction boundaries: tool names and LLM participation do not prove network communication; sending verbs, recipient identifiers, and executor labels are not communication-mechanism evidence. Choose remote/net_send/net_receive only when the source, code, or interface establishes network transport; otherwise retain a known tool at tool/recipient/null under EM12; ordinary return does not prove user-facing output. Model observation, network delivery, and user output are separate boundaries. Preserving possible observation of a container does not broaden later API arguments: delivery must retain actual selected values, input order, result identities, and explicit prohibitions. Lack of a concrete getter or execution framework alone does not disable the declared defaults. Preserve calculable partial order; report a semantic failure only when a necessary relation cannot be represented or assessed."),
    ("EM07", "Runtime-context writes: context_write requires evidence of creating, updating, or deleting runtime context content or bindings that later actions can read, including shared session state and environment variables. Merely producing an IR result is not a context write. File writes and model observation do not automatically imply context_write; each effect requires its own evidence. Saving unchanged content does not imply transform. Deleting a binding does not imply reading, transforming, or observing its former content. This classification rule does not establish an otherwise unrecorded write."),
    ("EM08", "Symbolic transfer boundary: preserve relevant input scope unless an explicit selection, deletion, replacement, or isolation supports reduction. Unknown computations retain possible input dependencies without claiming that all input plaintext survives. Unknown content in an identified source is not an unknown address and must not make that source alias unrelated locations. A dynamic or unidentified location uses a symbolic: name and cannot justify a definite overwrite or deletion. Partial effect order cannot justify observing only a cleaned result; retain supported original and later candidates. Source wholes may exist without being observed; data registration alone never creates a delivery. This stage declares symbolic operations, not propagated Data identities, sensitive-data sets, or DOE judgments."),
    ("EM09", "Acquisition and computation differ: returned tool or collection content has an acquisition boundary not exhausted by query inputs. Preserve that boundary, actual request inputs, and possible dependencies. Established remote receipt uses receive at a remote location with net_receive; known tool acquisition without established networking uses receive at a tool location in a null-effect event. An explicitly pure calculation remains compute; an opaque computation preserves possible dependencies without inventing a new external source. Unknown networking does not erase known acquisition. Assess the returned content's possible model routing with EM02 and EM03 rather than inferring visibility from the tool name."),
    ("EM10", "Deterministic processing compilation: model mode declares model processing and requires llm among participating operators. Before model processing, observe its actually referenced external input versions; intermediate values computed within that same segment are not fresh external inputs; acquired read/receive outputs become observable after acquisition. Default mode retains possible observation of read/receive outputs and non-isolated transformation inputs; it does not observe receive request parameters merely because a response is acquired. Local mode requires explicit source or code/interface evidence and an explicit returns list; internal reads are not model observations, while declared returned values cross to the model after the local segment. Empty local returns means no content returned to the model by that segment. Deduplicate unchanged external symbolic references within one processing segment by value reference and its consumption condition. A conditional observation never subsumes a later unconditional consumption. Conditions needed for model processing are themselves observed when applicable; a definitely omitted build member consumes no member value. Preserve earlier whole-value observation even when a later request member is omitted. Preserve different segments and returned/acquired versions, without treating every intermediate computation as another model call. Generated model-observation effects do not automatically add llm to operator or sink to roles; retain the independently evidenced action labels. The compiler creates these observations from typed modes and references, not opcode or evidence keywords. A model may still misclassify a mode; compilation proves structural implications of the supplied mode, not its truth. IR order is fixed or partial. For partial order, preserve required definition/use and declared within-segment ordering; the compiler records observation-before-model-processing, acquisition-before-observation, and local-processing-before-return-observation constraints. Independent segments may interleave between primitive operations. Partial order is a computable may relation, not a semantic failure."),
    ("EM11", "Element scope and filtering: filter_items preserves selected input elements unchanged under its recorded predicate; the static analysis does not execute a natural-language predicate. for_each introduces one shared element binding per possible element so selections and delivery parameters retain that element's identity. It is an analysis scope, not an invented CFG loop or one measured call. Body locals do not escape; nested scopes and shared-state acquisition or mutation are unsupported. Selecting an explicit field with select_part preserves that exact part, while compute only records dependence and never proves a field was forwarded unchanged. A field named summary is not itself a summarization operation."),
    ("EM12", "Boundary properties and defaults: access_scope is task, recipient, shared, or public; retention is task, persistent, or null when a receiving boundary's retention is not modeled. Storage and runtime-context locations require non-null retention. A task-internal tool requires supported local execution and task-internal receiving scope; explicitly nonlocal tools use recipient. Unspecified tool deployment conservatively retains an external recipient possibility, without inventing net_send or asserting measured remote execution. Runtime context defaults to task access and task retention; explicit cross-task memory or cross-subject sharing changes the respective property. Files default to task access and persistent retention; task-limited retention requires an explicit temporary-use and cleanup mechanism, not a temp-sounding name. Model, remote, and user boundaries default to recipient access, with null retention unless explicit retention is supported. A locally hosted model remains a content-processing recipient. Public access and sharing require source, code, interface, or supported contract evidence. Null retention does not establish no saving, logging, or future reuse; do not invent unmentioned backend persistence. These properties characterize static boundaries, not sensitivity, necessity, risk, or execution success."),
    ("EM13", "Delivery and sink classification: distinguish actual request delivery, acquired tool response, and compiler-generated model observation of the relevant versions. A tool receive's request dependencies do not replace a deliver operation for an evidenced tool request. Known networking uses its existing net_send delivery; do not duplicate that same delivery as an external_tool sink. A tool delivery with no established network effect is a null-effect deliver to a tool location, including an explicit empty argument list for a known zero-argument request. Pure task-internal delivery remains a propagation relation but is not a DOE sink. Collect content delivery, write and model-observation operations, not profile sink roles. Deletion or unbinding delivers no old content; append exposes this step's appended input, not automatically all previous stored content. Compute boundary exposure_level deterministically: task-internal/task-limited is 0, task-internal persistent is 1, recipient or shared is 2, public is 3; retain the highest applicable level. Levels describe boundary access and retention only. Only levels 1-3 enter the sink list. Preserve different stages, versions and element scopes. Ordinary return still identifies values in CFG inputs and does not invent a caller location or delivery."),

    ("EM14", "Optional request members: construct known object fields from their actual value references, preserving original field identity. build members may have a Boolean when reference: true includes the original value, false omits the member without consuming its value, and an abstract Boolean retains both possibilities. Identical condition references share one decision within a construction, so jointly controlled fields are not independently mixed. Conditions are control inputs, not request contents; do not add existence flags as payload merely because they govern optional parameters. Reject explicit non-Boolean controls instead of truthiness coercion. A possible true branch still requires a member value. Conditions do not narrow previously acquired or observed wholes, and are not a Data/path-condition system. Compiler-generated conditional observations use the same member condition, observing the condition separately when required and observing the member only when it may be consumed. This is symbolic parameter construction, not a claim about wire serialization."),
    ("EM15", "Request delivery and acquisition: define one request value from actual parameter values and reference it consistently in deliver.inputs and the corresponding receive.inputs. At one IR and element scope, request/response association requires the same boundary and exactly the same ordered symbolic request references. One delivery matches at most one response; ambiguous matches are an explicit binding failure, not a closest-position, name-similarity, or FIFO guess. Acquisition reuses the matched delivery's actual input bindings, including literal identities and data versions, and follows its delivery. Known zero-argument calls and acquisition with no request remain possible under their existing rules. Response inputs describe request influence, not response contents and not a replacement for request delivery."),


)


def execution_model() -> dict[str, Any]:
    """Return an isolated copy of the one supported abstract runtime contract."""
    return {"version": CONTRACT_VERSION,
            "rules": [{"id": rule_id, "text": text} for rule_id, text in _RULES]}


def _sha256(value: Any) -> str:
    text = json.dumps(value, ensure_ascii=False, sort_keys=True,
                      separators=(",", ":"), allow_nan=False)
    return hashlib.sha256(text.encode("utf-8")).hexdigest()


def validate_execution_model(model: Any) -> dict[str, Any]:
    """Reject old, altered, or expanded rules; never silently substitute them."""
    expected = execution_model()
    if (type(model) is not dict or set(model) != {"version", "rules"}
            or type(model.get("version")) is not str
            or model["version"] != CONTRACT_VERSION
            or type(model.get("rules")) is not list
            or any(type(rule) is not dict or set(rule) != {"id", "text"}
                   or type(rule["id"]) is not str or type(rule["text"]) is not str
                   for rule in model["rules"])
            or model != expected):
        raise ValueError("Abstract runtime contract identity mismatch: unsupported version or altered rules")
    return deepcopy(model)


def execution_model_binding(model: Any) -> dict[str, str]:
    """Bind the complete validated rule text using the recording digest format."""
    checked = validate_execution_model(model)
    return {"version": checked["version"], "sha256": _sha256(checked)}


def validate_execution_model_binding(binding: Any) -> dict[str, str]:
    """Validate the exact two-field identity of the supported contract."""
    expected = execution_model_binding(execution_model())
    if (type(binding) is not dict or set(binding) != {"version", "sha256"}
            or any(type(binding[key]) is not str for key in binding)
            or binding != expected):
        raise ValueError("Abstract runtime contract binding mismatch: unsupported version or digest")
    return deepcopy(binding)
