"""Render a canonical Skill IR control-flow graph as Mermaid."""

from __future__ import annotations

import html
import json
from typing import Any

from skillflow.graph.ir import Operand
from skillflow.graph.ir import OperandType
from skillflow.graph.ir.cfg import ControlFlowGraph


def render_mermaid(cfg: ControlFlowGraph) -> str:
    """Render a validated CFG as a Mermaid top-down flowchart."""

    if not isinstance(cfg, ControlFlowGraph):
        raise TypeError("cfg must be a ControlFlowGraph")
    cfg.validate_integrity()

    block_nodes = {
        block_id: f"block_node_{index:03d}"
        for index, block_id in enumerate(cfg.blocks, start=1)
    }
    resources, resource_links = _collect_external_resources(cfg)
    resource_nodes = {
        identifier: f"resource_node_{index:03d}"
        for index, identifier in enumerate(resources, start=1)
    }
    # The two summary lines below list values by canonical ID and have no
    # operand to read the extractor's wording off, so they look it up here.
    result_semantic_names = cfg.result_semantic_names()

    lines = [
        "flowchart TD",
        "  %% Auto-generated by skill-ir",
    ]

    for block_id, block in cfg.blocks.items():
        node_id = block_nodes[block_id]
        label_lines = [
            f"<b>{_escape_label(block_id)}</b>: {_escape_label(block.block_name)}"
        ]
        if block.data_source_kind:
            description = (
                "上下文读入" if block.data_source_kind == "context" else "外部数据读入"
            )
            label_lines.append(
                f"<b>source · {block.data_source_kind}（{description}）</b>"
            )
        incoming = block.cross_block_result_ids()
        if incoming:
            label_lines.append(
                "引用其他块的结果："
                + ", ".join(
                    _result_label(identifier, result_semantic_names)
                    for identifier in incoming
                )
            )
        label_lines.extend(
            _instruction_label(instruction) for instruction in block.instructions
        )
        produced = block.produced_result_ids()
        if produced:
            label_lines.append(
                "产出："
                + ", ".join(
                    _result_label(identifier, result_semantic_names)
                    for identifier in produced
                )
            )
        label = "<br/>".join(label_lines)
        lines.append(f'  {node_id}["{label}"]')

    for resource_name in resources:
        node_id = resource_nodes[resource_name]
        label = f"external_resource: {_escape_label(resource_name)}<br/>资源标识"
        lines.append(f'  {node_id}(["{label}"])')

    for edge in cfg.edges:
        source = block_nodes[edge.source_block_id]
        target = block_nodes[edge.target_block_id]
        if edge.condition_text:
            lines.append(
                f"  {source} -->|{_escape_edge_label(edge.condition_text)}| {target}"
            )
        else:
            lines.append(f"  {source} --> {target}")

    for resource_name in resources:
        resource_node = resource_nodes[resource_name]
        for block_id in resource_links[resource_name]:
            lines.append(
                f"  {resource_node} -.->|external_resource| {block_nodes[block_id]}"
            )

    lines.extend(
        [
            "",
            "  classDef block fill:#F8FAFC,stroke:#334155,color:#0F172A,stroke-width:1px;",
            "  classDef source fill:#D1FAE5,stroke:#047857,color:#064E3B,stroke-width:2px;",
            "  classDef entry stroke:#1D4ED8,stroke-width:3px;",
            "  classDef resource fill:#FEF3C7,stroke:#B45309,color:#451A03,stroke-width:1px;",
            f"  class {','.join(block_nodes.values())} block;",
        ]
    )
    source_nodes = [
        node_id
        for block_id, node_id in block_nodes.items()
        if cfg.blocks[block_id].data_source_kind is not None
    ]
    if source_nodes:
        lines.append(f"  class {','.join(source_nodes)} source;")
    lines.append(f"  class {block_nodes[cfg.entry_block_id]} entry;")
    if resource_nodes:
        lines.append(f"  class {','.join(resource_nodes.values())} resource;")

    return "\n".join(lines) + "\n"


def _collect_external_resources(
    cfg: ControlFlowGraph,
) -> tuple[list[str], dict[str, list[str]]]:
    resources: list[str] = []
    links: dict[str, list[str]] = {}
    seen_resources: set[str] = set()

    for block_id, block in cfg.blocks.items():
        block_resources: set[str] = set()
        for instruction in block.instructions:
            for operand in instruction.inputs:
                if (
                    operand.type is not OperandType.EXTERNAL_RESOURCE
                    or operand.identifier is None
                ):
                    continue
                resource_name = operand.identifier
                if resource_name not in seen_resources:
                    seen_resources.add(resource_name)
                    resources.append(resource_name)
                    links[resource_name] = []
                block_resources.add(resource_name)
        for resource_name in block_resources:
            if block_id not in links[resource_name]:
                links[resource_name].append(block_id)

    return resources, links


def _instruction_label(instruction: Any) -> str:
    parts = [
        f"<code>{_escape_label(instruction.id)}</code>: "
        f"<code>{_escape_label(instruction.opcode)}</code>"
    ]
    if instruction.inputs:
        prefix = (
            "读取上下文："
            if any(item.type is OperandType.CONTEXT_KEY for item in instruction.inputs)
            else "输入："
        )
        parts.append(
            prefix
            + ", ".join(_operand_label(operand) for operand in instruction.inputs)
        )
    if instruction.outputs:
        parts.append(
            "产出："
            + ", ".join(_operand_label(operand) for operand in instruction.outputs)
        )
    return " · ".join(parts)


def _operand_label(operand: Operand) -> str:
    if operand.type is OperandType.LITERAL:
        value = json.dumps(
            operand.literal_value, ensure_ascii=False, separators=(",", ":")
        )
        return f"literal:{_escape_label(value)}"
    identifier = operand.identifier or ""
    if operand.type is OperandType.RESULT:
        names = (
            {identifier: operand.semantic_name}
            if operand.semantic_name and operand.semantic_name != identifier
            else {}
        )
        return _result_label(identifier, names)
    label = f"{_escape_label(operand.type.value)}:{_escape_label(identifier)}"
    # Resources keep their identifiers; show any additional semantic label only
    # when the extractor used wording that differs from that identifier.
    if operand.semantic_name and operand.semantic_name != identifier:
        label += f" ({_escape_label(operand.semantic_name)})"
    return label


def _result_label(result_id: str, result_semantic_names: dict[str, str]) -> str:
    """Show the semantic name first, followed by the stable result ID."""

    semantic_name = result_semantic_names.get(result_id)
    if semantic_name:
        return f"{_escape_label(semantic_name)}（{_escape_label(result_id)}）"
    return _escape_label(result_id)


def _escape_label(value: object) -> str:
    text = " ".join(str(value).split())
    # Mermaid labels are double-quoted. Literal apostrophes are safe, whereas
    # html.escape's hexadecimal &#x27; is displayed verbatim by Mermaid.
    return html.escape(text, quote=False).replace('"', "&quot;").replace("|", "&#124;")


def _escape_edge_label(value: object) -> str:
    return _escape_label(value)
